# Generated by Django 3.2.8 on 2021-10-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_title', models.CharField(max_length=30)),
                ('latest_time', models.CharField(max_length=30)),
                ('pollutant_name', models.CharField(max_length=30)),
                ('pollutant_unit', models.CharField(max_length=30)),
                ('pollutant_value', models.IntegerField(max_length=4)),
            ],
        ),
    ]
